# Generated by Django 5.0.1 on 2024-01-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
